ALTER TABLE Jogo ADD IdSelo INT NOT NULL DEFAULT 1
ALTER TABLE Jogo
ADD CONSTRAINT fk_Selo
FOREIGN KEY (IdSelo)
REFERENCES Selo(Id)

ALTER TABLE Jogo ADD Descricao VARCHAR(8000) NULL
ALTER TABLE Jogo ADD Url_Imagem VARCHAR(8000) NULL
ALTER TABLE Jogo ADD Tag_Video VARCHAR(8000) NULL
GO;

UPDATE Jogo SET Descricao = 'SEM DESCRIÇÃO'
ALTER TABLE Jogo ALTER COLUMN Descricao VARCHAR(8000) NOT NULL
GO;