ALTER TABLE Jogo 
	ADD Descricao VARCHAR(500) DEFAULT('SEM DESCRICAO') NOT NULL,
		IdSelo INT DEFAULT(3) NOT NULL,
		Imagem VARCHAR(500) NULL,
		Video VARCHAR(500) NULL,
	CONSTRAINT FK_IdSelo FOREIGN KEY (IdSelo) REFERENCES Selo(Id);