
CREATE PROCEDURE PRC_RELATORIO_PEDIDOS_MES( @pIDCliente INT )
AS
BEGIN

SELECT DATEPART(MONTH, P.DataPedido) AS MES, 
	   COUNT(DISTINCT P.IDPedido ) AS TOTAL_PEDIDOS, 
	   SUM(DISTINCT P.ValorPedido) AS VALOR_TOTAL,
	   COUNT( DISTINCT PIT.IDProduto) AS TOTAL_PRODUTOS
FROM Pedido P
	LEFT JOIN PedidoItem PIT ON PIT.IDPedido = P.IDPedido
WHERE IDCliente = @pIDCliente
AND MONTH(P.DataPedido) BETWEEN MONTH(GETDATE())-6 
							AND MONTH(GETDATE()) 
							AND YEAR(GETDATE()) = YEAR(P.DataPedido) 
GROUP BY MONTH(P.DataPedido)


END


